config/routes.rb
Rails.application.routes.draw do
  #get 'collection/index'
  get '/:collection/', to: 'collection#index', as: 'collection'
  get '/:collection/contract', to: 'collection#contract', as: 'contract'
  get '/:collection/:item', to: 'item#index', as: 'item'
  get '/api/:collection/:id', to: 'item_api#index', as: 'api_item'
  root 'page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def data
    @data ||= HashWithIndifferentAccess.new(
      YAML.load_file(Rails.root.join('config/data.yml'))
    )
  end
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController
  before_action :check_existance

  def index
    @collection = data[params[:collection]]
  end

  def contract
    collection = data[params[:collection]]

    render json: {
      description: collection[:description],
      name: collection[:title],
      image: "#{root_url}icon.png",
      external_link: "#{root_url}#{collection[:slug]}"
    }
  end

  private
  def check_existance
    return if data.dig params[:collection]

    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/item_api_controller.rb
class ItemApiController < ApplicationController
  include ApplicationHelper
  before_action :check_existance

  def index
    collection = data.dig(params[:collection])
    item_id = params[:id].to_i
    item_key = collection[:items].keys.select do |key|
      collection[:items][key][:id] == item_id
    end

    raise ActionController::RoutingError.new('Not Found') if item_key.empty?

    item = collection[:items][item_key.first]
    render json: {
      id: item_id,
      name: item[:title],
      description: item[:description],
      external_url: "#{root_url}#{collection[:slug]}/#{item[:slug]}",
      image: "#{root_url}#{item_image_url(collection[:slug], item[:slug])}",
      attributes: [{count: 1}]
    }
  end

  private

  def check_existance
    return if data.dig(params[:collection])

    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  before_action :check_existance

  def index
    @item = data.dig(params[:collection], :items, params[:item])
    @collection = data[params[:collection]]

    owner = Struct.new(:address, :buy_at)
    #@owners = [["0x123456781233", Date.today],["0x3423456225", Date.today]]
    @owners = [].map { |o| owner.new(o.first, o.last) }

  end

  private

  def check_existance
    return if data.dig(params[:collection], :items, params[:item])

    raise ActionController::RoutingError.new('Not Found')
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    @collection = data['top-ten-classic-sci-fi']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def item_image_url(collection, item)
    "/#{collection}/original/#{item}.jpg"
  end

  def item_image_url_thumbnail(collection, item)
    "/#{collection}/thumbnail/#{item}.jpg"
  end
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/collection/index.html.erb
<% content_for :title, @collection[:title] %>

<section class="section">
  <div class="container">

    <div class="tags has-addons">
      <span class="tag">Collection</span>
      <span class="tag is-primary">10 pieces</span>
    </div>

    <h2 class="subtitle is-3">
      <%= @collection[:title] %>
    </h2>

    <p class='mb-5'>

    <% counter=0 %> 
    <% for item_key in @collection[:items].keys %>
      <% item = @collection[:items][item_key] %>
      <% if counter % 3 == 0 %>
      <div class="tile is-ancestor">
      <% end %>
        <div class="tile is-parent is-4">
          <div class='tile is-child box'>
            <%= link_to item_path({collection: @collection[:slug], item: item[:slug]}) do %>
              <figure class="image mb-3">
                <%=
                    image_tag item_image_url(@collection[:slug], item[:slug]),
                    alt: item[:title]
                %>
              </figure>
              <span class='is-size-6'><%= item[:title]%></span>
            <% end %>
          </div>
        </div>
      <% counter =counter+1%>
      <% if counter % 3 == 0 %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>
</section>

app/views/item/index.html.erb
<% content_for :title, @item[:title] %>
<section class="section">
  <div class="container">

    <div class="columns is-vcentered">
      <div class="column">
        <figure class="image mb-3 has-text-centered" style="width: 300px; margin: auto;box-shadow: 0.5em 0.5em 1em -0.5em rgba(10, 10, 10, 0.3), 0 0px 0 1px rgba(10, 10, 10, 0.1);border: 1px solid #8a8888;">
          <%=
              image_tag item_image_url(@collection[:slug], @item[:slug]),
              alt: @item[:title]
          %>
        </figure>
      </div>
      <div class="column">
        <h1 class="subtitle is-4">
          <%= @item[:title] %>
        </h1>
        <h2 class="subtitle is-6">
          <%= @item[:author] %>,
          <%= @item[:published_at] %>
        </h2>
        <div class="tags has-addons">
          <span class="tag">
            <%= link_to 'This item on blockchain', "#{@collection[:contract_address]}?a=#{@item[:id]}" %>
          </span>
          <span class="tag is-primary">ERC721</span>
        </div>
        <div class="tags has-addons">
          <span class="tag">
            <%= link_to @collection[:title], collection_path({collection: @collection[:slug]}) %>
          </span>
          <span class="tag is-primary">10 items</span>
        </div>
        <div class="tags has-addons">
          <span class="tag">Number of Copies</span>
          <span class="tag is-primary"><%= @item[:count] %></span>
        </div>
        <%= link_to "#{@collection[:opensea_store]}/#{@item[:id]}" do %>
          <button class="button is-active is-success is-medium">
            Own this item on blockchain
          </button>
        <% end %>
        <div style="font-size: 0.7rem; padding-top:5px">
          Powered by OpenSea
          <%= image_tag "/opensea-logo.png", style: "display: inline-block; margin-bottom: -4px;", class: 'image is-16x16' %>
        </div>
      </div>
    </div>

    <div class="columns mt-6 mb-6">
      <div class="column is-1"></div>
      <div class="column">
        <p class="subtitle">
          <%= @item[:description] %>
        </p>
      </div>
      <div class="column is-1"></div>
    </div>

    <% unless @owners.empty? %>
    <div class="columns">
      <div class="column is-2"></div>
      <div class="column is-8">
        <table class="table is-bordered is-striped is-hoverable is-fullwidth">
          <thead>
            <tr>
              <td>
                Owner
              </td>
              <td>
                Buy at
              </td>
            </tr>
          </thead>
          <tbody>
            <% for owner in @owners %>
            <tr>
              <td>
                <%= owner.address %>
              </td>
              <td>
                <%= owner.buy_at %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="column is-2"></div>
    </div>
    <% end %>


    <div class="columns">
      <div class="column is-2"></div>
      <div class="column is-8">
        <p>
        This item is part of a <%= @collection[:title] %> collection. You can own this one sperately or you can own all the items in the collection. Below you can see rest of the collection.
        </p>
      </div>
      <div class="column is-2"></div>
    </div>
    <div class="columns">
      <div class="column is-2"></div>
      <% for item_key in @collection[:items].keys %>
        <% item = @collection[:items][item_key] %>
        <% next if item[:id] == @item[:id] %> 
      <div class="column is-one-third-mobile">
        <div class="card">
          <div class="card-image">
            <%= link_to item_path({collection: @collection[:slug], item: item[:slug]}) do %>
              <figure class="image">
                <%=
                    image_tag item_image_url_thumbnail(@collection[:slug], item[:slug]),
                      alt: item[:title]
                %>
              </figure>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <div class="column is-2"></div>
      </div>


    </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>XCGRADUS</strong> by a team of blockchain & sci fi lovers. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<section class="hero is-small is-dark is-bold">
  <div class="hero-body" style="background: url('/header-bg.jpg');background-size: cover;">
    <div class="container">
      <h1 class="subtitle is-4 mb-0">
        <a href='/' class='has-text-white'>
          <%= image_tag "/icon.png", style: "display: inline-block", class: 'image is-16x16' %>
          XCGRADUS
        </a>
      </h1>
      <h2 class="subtitle is-6 ml-5">
        Rare digital paintings on <strong>Blockchain</strong>
      </h2>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "XCGRADUS | #{yield(:title)}" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag '/icon.png' %>
  </head>

  <body>
    <%= render "layouts/header" unless params[:controller] == 'page' %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/page/index.html.erb
<% content_for :title, 'Home' %>
<section class="hero is-medium is-dark is-bold">
  <div class="hero-body" style="background: url('/header-bg.jpg');background-size: cover;">
    <div class="container">
      <h1 class="subtitle is-2 mb-0">
        <%= image_tag "/icon.png", style: "display: inline-block", class: 'image is-32x32' %>
        XCGRADUS
      </h1>
      <h2 class="subtitle is-5 ml-6">
        Rare digital paintings on <strong>Blockchain</strong>
      </h2>
      <h3 class="ml-6">
        The paintings are <a href='https://academy.binance.com/glossary/non-fungible-token-nft'>Non Fungible Tokens (NFT)</a>, each one of them has a unique identity stored in Ethereum blockchain.
        <br />
        Store or trade them directly from your Ethereum wallet.
        <br />
      </h3>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="tags has-addons">
      <span class="tag">Collection</span>
      <span class="tag is-primary">10 pieces</span>
    </div>
    <h2 class="subtitle is-3">
      <%= @collection[:title] %>
    </h2>
    <p class='mb-5'>
    <%=  @collection[:description] %>
    </p>
    <div class="tile is-ancestor">
      <% for item_key in @collection[:items].keys[0..2] %>
        <% item = @collection[:items][item_key] %>
        <div class="tile is-parent">
          <div class='tile is-child box'>
            <%= link_to item_path({collection: @collection[:slug], item: item[:slug]}) do %>
              <figure class="image mb-3">
              <%=
                  image_tag item_image_url(@collection[:slug], item[:slug]),
                  alt: item[:title]
                %>
              </figure>
              <span class='is-size-6'><%= item[:title]%></span>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="tile is-ancestor">
      <div class="tile is-parent">
        <div class="tile is-child">
          <%= link_to collection_path({collection: @collection[:slug]}) do %>
            <button class="button is-link">See the collection page</button
          <% end %>
        </div>
      </div>
    </div>

  </div>
</section>